# Generated by Django 4.0.4 on 2022-04-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
