# Generated by Django 4.0.4 on 2022-04-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_app', '0002_rename_f_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quality',
            old_name='param_name',
            new_name='parameter_name',
        ),
        migrations.RenameField(
            model_name='quality',
            old_name='temp_name',
            new_name='template_name',
        ),
    ]
